import type { Metadata } from "next";
import {
	Indie_Flower,
	Geist,
	Gluten,
	Patrick_Hand,
	Gloria_Hallelujah,
} from "next/font/google";

import "./globals.css";
// Default styles that can be overridden by your app
import "@solana/wallet-adapter-react-ui/styles.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const indieFlower = Gloria_Hallelujah({
	weight: "400",
	variable: "--font-handwriting",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${indieFlower.variable} antialiased`}
			>
				<Providers>
					<main className="h-dvh overflow-y-auto relative font-handwriting">
						<div className="absolute top-0 left-0 h-16 w-full flex justify-between px-6 py-4">
							<h1 className="text-2xl font-bold font-handwriting">
								reSOLution
							</h1>
						</div>
						{children}
					</main>
					<Toaster />
				</Providers>
			</body>
		</html>
	);
}
